export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_REGISTER = 'USER_REGISTER';
export const USER = 'USER';

export const FETCH_PROUDS_REQUEST = 'FETCH_PROUDS_REQUEST';
export const FETCH_PROUDS_SUCCESS = 'FETCH_PROUDS_SUCCESS';
export const FETCH_PROUDS_FAILURE = 'FETCH_PROUDS_FAILURE';

export const FETCH_SKILLS_REQUEST = 'FETCH_SKILLS_REQUEST';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE';

export const FETCH_EDUCATIONS_REQUEST = 'FETCH_EDUCATIONS_REQUEST';
export const FETCH_EDUCATIONS_SUCCESS = 'FETCH_EDUCATIONS_SUCCESS';
export const FETCH_EDUCATIONS_FAILURE = 'FETCH_EDUCATIONS_FAILURE';

export const ADD_PROUD = 'ADD_PROUD';
export const REM_PROUD = 'REM_PROUD';
export const EDITING_PROUD = 'EDITING_PROUD';

export const ADD_SKILL = 'ADD_SKILL';
export const ADD_EDUCATION = 'ADD_EDUCATION';
